version: '3.8'

services:
  web:
    build: .
    container_name: akaf_web
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=0
    restart: always

volumes:
  static_volume:
  media_volume:
