# Generated by Django 6.0.2 on 2026-02-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='photo_in',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/%Y/%m/', verbose_name='Photo In'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='photo_out',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/%Y/%m/', verbose_name='Photo Out'),
        ),
    ]
