# Generated by Django 6.0.2 on 2026-02-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_attendance', '0002_attendance_latitude_attendance_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='photo_in',
            field=models.TextField(blank=True, null=True, verbose_name='Photo In'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='photo_out',
            field=models.TextField(blank=True, null=True, verbose_name='Photo Out'),
        ),
    ]
