# Generated by Django 6.0.2 on 2026-02-12 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcomment',
            name='attachment',
        ),
        migrations.AddField(
            model_name='ticket',
            name='remote_software_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Remote Software ID'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='remote_software_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Remote Software Name'),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/%Y/%m/', verbose_name='File')),
                ('file_type', models.CharField(choices=[('file', 'File'), ('voice', 'Voice'), ('video', 'Video')], default='file', max_length=10, verbose_name='File Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ticketing.ticketcomment')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ticketing.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Attachment',
                'verbose_name_plural': 'Ticket Attachments',
            },
        ),
    ]
