# Generated by Django 6.0.2 on 2026-02-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_remove_ticketcomment_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('waiting_response', 'Waiting for Response'), ('under_review', 'Under Review'), ('referred', 'Referred to Expert'), ('in_progress', 'In Progress'), ('needs_info', 'Needs More Info'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status'),
        ),
    ]
