# Generated by Django 6.0.2 on 2026-02-09 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('ar', 'Arabic'), ('ur', 'Urdu'), ('hi', 'Hindi'), ('tr', 'Turkish')], default='en', max_length=10)),
                ('currency_code', models.CharField(default='OMR', help_text='ISO 4217 Currency Code (e.g. OMR, USD)', max_length=10)),
                ('currency_symbol', models.CharField(default='ر.ع.', help_text='Currency Symbol (e.g. $, €)', max_length=10)),
                ('currency_decimal_places', models.IntegerField(default=3, help_text='Number of decimal places (e.g. 3 for OMR, 2 for USD)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
