# Generated by Django 6.0.2 on 2026-02-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_access_expenses', 'Can access Expense Manager'), ('can_access_ticketing', 'Can access Ticketing System'), ('can_access_projects', 'Can access Project Control'), ('can_access_dms', 'Can access Document DMS'), ('can_access_ai', 'Can access AI Engine'), ('can_access_menu', 'Can access Digital Menu'), ('can_access_club', 'Can access Customer Club')]},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
