# Generated by Django 6.0.2 on 2026-02-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency_code',
            field=models.CharField(default='OMR', help_text='ISO 4217 Currency Code (e.g. OMR, USD)', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currency_decimal_places',
            field=models.IntegerField(default=3, help_text='Number of decimal places (e.g. 3 for OMR, 2 for USD)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currency_symbol',
            field=models.CharField(default='ر.ع.', help_text='Currency Symbol (e.g. $, €)', max_length=10),
        ),
    ]
