# Generated by Django 6.0.2 on 2026-02-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_options_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='require_photo',
            field=models.BooleanField(default=True, help_text='Require a photo for attendance clock-in/out'),
        ),
    ]
