# Generated by Django 6.0.2 on 2026-02-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='claim_reimbursement',
            field=models.BooleanField(default=True, verbose_name='Claim Reimbursement'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='currency',
            field=models.CharField(default='OMR', max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('petty_cash', 'Petty Cash'), ('undeposited_funds', 'Undeposited Funds'), ('personal_card', 'Personal Card'), ('company_card', 'Company Card')], help_text='Required if Reimbursement is OFF', max_length=50, null=True, verbose_name='Payment Mode'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference #'),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='business_purpose',
            field=models.TextField(blank=True, null=True, verbose_name='Business Purpose'),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Duration To'),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Duration From'),
        ),
    ]
