# Generated by Django 6.0.2 on 2026-02-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenseitem_claim_reimbursement_expenseitem_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='expenses.expensereport'),
        ),
    ]
