# Generated by Django 6.0.2 on 2026-02-07 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expenseitem_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='merchant',
            field=models.CharField(blank=True, help_text='e.g. Shell, Starbucks', max_length=100, null=True, verbose_name='Merchant'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Trip Name')),
                ('travel_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', max_length=20, verbose_name='Travel Type')),
                ('business_purpose', models.TextField(blank=True, null=True, verbose_name='Business Purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(default='OMR', max_length=10, verbose_name='Currency')),
                ('date', models.DateField(verbose_name='Date')),
                ('paid_through', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check')], max_length=50, null=True, verbose_name='Paid Through')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference #')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='expenses.expensereport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='expenses.trip')),
            ],
        ),
        migrations.AddField(
            model_name='expensereport',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='expenses.trip'),
        ),
    ]
