# Generated by Django 6.0.2 on 2026-02-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expenseitem_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensereport',
            options={'verbose_name': 'Statement', 'verbose_name_plural': 'Statements'},
        ),
        migrations.AlterField(
            model_name='advance',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
    ]
