# Generated by Django 6.0.2 on 2026-02-09 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g. Site Visit Expenses 2026-02-07', max_length=200, verbose_name='Report Title')),
                ('business_purpose', models.TextField(blank=True, null=True, verbose_name='Business Purpose')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Duration From')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Duration To')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='OMR', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statement',
                'verbose_name_plural': 'Statements',
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Expense Date')),
                ('merchant', models.CharField(blank=True, help_text='e.g. Shell, Starbucks', max_length=100, null=True, verbose_name='Merchant')),
                ('category', models.CharField(help_text='e.g. Food, Transport, Material', max_length=100, verbose_name='Category')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference #')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='OMR', max_length=10, verbose_name='Currency')),
                ('claim_reimbursement', models.BooleanField(default=True, verbose_name='Claim Reimbursement')),
                ('payment_mode', models.CharField(blank=True, choices=[('petty_cash', 'Petty Cash'), ('undeposited_funds', 'Undeposited Funds'), ('personal_card', 'Personal Card'), ('company_card', 'Company Card')], help_text='Required if Reimbursement is OFF', max_length=50, null=True, verbose_name='Payment Mode')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Receipt Image')),
                ('is_ai_scanned', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(default=0.0, help_text='AI Confidence Score (0-1)')),
                ('raw_ocr_text', models.TextField(blank=True, help_text='Raw text extracted from receipt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='expenses.expensereport')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Trip Name')),
                ('travel_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', max_length=20, verbose_name='Travel Type')),
                ('business_purpose', models.TextField(blank=True, null=True, verbose_name='Business Purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expensereport',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='expenses.trip'),
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(default='OMR', max_length=10, verbose_name='Currency')),
                ('date', models.DateField(verbose_name='Date')),
                ('paid_through', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check')], max_length=50, null=True, verbose_name='Paid Through')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference #')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='expenses.expensereport')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='expenses.trip')),
            ],
        ),
    ]
