# Generated by Django 6.0.2 on 2026-02-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('slug', models.SlugField(help_text='Used for URL routing (e.g., company-name)', unique=True, verbose_name='Subdomain/Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active Subscription')),
                ('subscription_end_date', models.DateField(blank=True, null=True, verbose_name='Subscription End Date')),
                ('can_use_expenses', models.BooleanField(default=False, verbose_name='Enable Expense Manager')),
                ('can_use_ticketing', models.BooleanField(default=False, verbose_name='Enable Ticketing System')),
                ('can_use_projects', models.BooleanField(default=False, verbose_name='Enable Project Control')),
                ('can_use_dms', models.BooleanField(default=False, verbose_name='Enable Document DMS')),
                ('can_use_ai', models.BooleanField(default=False, verbose_name='Enable AI Engine')),
                ('can_use_menu', models.BooleanField(default=False, verbose_name='Enable Digital Menu')),
                ('can_use_club', models.BooleanField(default=False, verbose_name='Enable Customer Club')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
